### ISSUE TITLE
Vertical vs horizontal doesnt display properly

### ISSUE THREAD

**Issue by CaptainJimmy** [Privacywonk/MMM-Surf#5]
![screenshot from 2017-12-05 12-20-01](https://user-images.githubusercontent.com/27983333/33621112-c69bb1da-d9b7-11e7-99b8-904af77478bd.png)

**Comment by CaptainJimmy** [comment]
Possible interim fix: 
    remove layout: "horizontal" from config example in REadme,
    hard code it inside MMM-Surf

**Comment by Privacywonk** [comment]
updated & working properly. Layout adjusts automagically.
